name = "apps"

[[steps]]
name = "flathub apps"
tool = "flatpak"
packages = [
  "com.saivert.pwvucontrol",
  "io.missioncenter.MissionCenter",
  "org.gnome.TextEditor",
  "org.kde.krita",
  "io.mpv.Mpv",
  "org.telegram.desktop",
]
