name = "hyprland"

[[steps]]
name = "repos"
tool = "add_repo"
packages = ["erikeider/SwayNotificationCenter"]

[[steps]]
name = "packages"
tool = "install"
packages = [
  "sddm",
  "hyprland",
  "hyprlock",
  "SwayNotificationCenter",
  "swaybg",
  "xfce-polkit",
  "wlogout",
  "waybar",
  "network-manager-applet",
  "blueman",
  "kitty",
  "xdg-desktop-portal",
  "qt5ct",
  "qt6ct",
  "wdisplays",
] # wireplumber?

[[steps]]
name = "soft"
tool = "install"
packages = ["firefox", "thunar", "gnome-keyring"]

[[steps]]
name = "wallust"
tool = "cargo"
packages = ["wallust"]

[[steps]]
name = "git credentiol manager"
cmd = [
  "sudo dnf install -y dotnet-sdk-8.0",
  "dotnet tool install -g git-credential-manager",
  "git-credential-manager configure",
  "git config --global credential.credentialStore secretservice",
]

[[steps]]
name = "set arc theme"
cmd = [
  "sudo dnf install -y arc-theme",
  "gsettings set org.gnome.desktop.interface gtk-theme Arc-Dark",
  "gsettings set org.gnome.desktop.interface icon-theme Arc-Dark",
]
